export const CREATE_BOOKING_PENDING = 'CREATE_BOOKING_PENDING';
export const GET_BOOKING_PENDING = 'GET_BOOKING_PENDING';

export const SET_BOOKING = 'SET_BOOKING';

export const BOOKING_API_ERROR = 'BOOKING_API_ERROR';
