export const SET_COUNSELLOR_DATA = 'SET_COUNSELLOR_DATA';
export const SET_ALL_COUNSELLORS_DATA = 'SET_ALL_COUNSELLORS_DATA';

export const GET_COUNSELLOR_DATA_PENDING = 'GET_COUNSELLOR_DATA_PENDING';
export const GET_ALL_COUNSELLORS_PENDING = 'GET_ALL_COUNSELLORS_PENDING';

export const COUNSELLOR_API_ERROR = 'COUNSELLOR_API_ERROR';
